language: node_js
node_js:
  - "6"
  - "4"
  - "0.12"
  - "0.10"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - ./es2015-test.sh
  - npm test
notifications:
  email: false
